services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: laravel_app_apache_mine
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./laravel.conf:/etc/apache2/sites-available/000-default.conf  # Mount custom config
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - laravel_network

  db:
    image: mysql:latest
    container_name: laravel_db_mysql_mine
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_mine
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
    name: laravel_network
    # external: true
volumes:
    db_data:
        # driver: local
        name: db_data
